package config

const (
	// Token 线上token
	Token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEyNDM3NjYsIkxvZ2luVmVyaWZ5IjoxLCJVbmlxdWVUb2tlbiI6IjRiMjQ0MDZiLWM0NDAtNGUyYS1hMmJiLTIzNzAzZGU3MTNkNyIsIkFnZW50Ijoid2ViIiwiZXhwIjoxNzE3OTg4Nzk3fQ.fUv-89dRAqhrPoVdZy7HIUD7O1gqk96hZl_s7tm-gEk"
	// Token 合约运营后台token
	//Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTY4Mjc4MDksInVzZXJJZCI6OSwidXNlcm5hbWUiOiJHZW9yZ2UwMDEifQ.4HegmOrO7doAu34YASgCe04dDx6ANhcwYMbsFUAxd-c"
)
